---
title: "Relationship"
author: "Xiaotai Chai"
date: "11/6/2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(data.table)
library(ggplot2)
library(tidyverse)
```


# Set working directory  
```{r}
# double check that this puts you in the right dir
project.dir <- getwd()
setwd(project.dir)
dataset.dir <- "Data"
outputs.dir <- "Output"
```

# Read in cleaned csv file
```{r}
# todo replace with fread
outcomes2013 <- fread("filtered_2013.csv", na.strings=c("<NA>","PrivacySuppressed"))
#head(outcomes2013)
```

# Find relationship between completion within 4 years at original institution and Gender of student
```{r}
female_complete4yr <- as.numeric(outcomes2013$FEMALE_COMP_ORIG_YR4_RT)
male_complete4yr <- as.numeric(outcomes2013$MALE_COMP_ORIG_YR4_RT)
num_completed_by_gender <- na.omit(data.frame(female_complete4yr,male_complete4yr))  # omit rows were either F or M is NA

plot(num_completed_by_gender, xlab="# females graduated", ylab="# males graduated")+title("# of graduates, male vs female")

lm.fit <- lm(female_complete4yr ~ male_complete4yr, data = num_completed_by_gender)
summary(lm.fit)
plot(lm.fit)

MEAN <- c(mean(as.numeric(outcomes2013$MALE_COMP_ORIG_YR4_RT),na.rm=TRUE), mean(as.numeric(outcomes2013$FEMALE_COMP_ORIG_YR4_RT),na.rm=TRUE)) 

STD <- c(sd(as.numeric(outcomes2013$MALE_COMP_ORIG_YR4_RT),na.rm=TRUE), sd(as.numeric(outcomes2013$FEMALE_COMP_ORIG_YR4_RT),na.rm=TRUE)) 

MEDIAN <- c(median(as.numeric(outcomes2013$MALE_COMP_ORIG_YR4_RT),na.rm=TRUE), median(as.numeric(outcomes2013$FEMALE_COMP_ORIG_YR4_RT),na.rm=TRUE)) 

mydata <- data.frame(MEAN, STD, MEDIAN)
row.names(mydata) <- c("male_complete4yr", "female_complete4yr")
mydata
```

# test verion of what's below
```{r}
ncf <- outcomes2013[outcomes2013$INSTNM == "New College of Florida",]
#ncf
```




# Compare ncf and other colleges
```{r}
ncf <- outcomes2013[outcomes2013$INSTNM == "New College of Florida",]

female_percent <- outcomes2013[,c("INSTNM","FEMALE")]
colnames(female_percent) <- c("School", "Value")
female_percent <- as.data.frame(mutate(female_percent, Feature="Percnt_female"))

percent_recv_loans <- outcomes2013[,c("INSTNM","PCTFLOAN")]
colnames(percent_recv_loans) <- c("School", "Value")
percent_recv_loans <- as.data.frame(mutate(percent_recv_loans, Feature="Percnt_reciv_loan"))

percnt_older_than_25yr <- outcomes2013[,c("INSTNM","UG25ABV")]
colnames(percnt_older_than_25yr) <- c("School", "Value")
percnt_older_than_25yr <- as.data.frame(mutate(percnt_older_than_25yr, Feature="Percnt_older_than_25yr"))

# Avg_fam_income <- outcomes2013[, c("INSTNM","FAMINC")]
# colnames(Avg_fam_income) <- c("School", "Value")
# Avg_fam_income <- as.data.frame(mutate(Avg_fam_income, Feature="Avg_fam_income"))

# mean_income_graduates_after_8yr <- outcomes2013[, c("INSTNM","MN_EARN_WNE_P8")]
# colnames(mean_income_graduates_after_8yr) <- c("School", "Value")
# mean_income_graduates_after_8yr <- as.data.frame(mutate(mean_income_graduates_after_8yr, Feature="Mean_income_graduates_after_8yr"))

#Share of students earning over $25,000/year (threshold earnings) 8 years after entry
perc_graduates_earning_grtrthn25k_peryer <- outcomes2013[,c("INSTNM","GT_25K_P8")]
colnames(perc_graduates_earning_grtrthn25k_peryer) <- c("School", "Value")
perc_graduates_earning_grtrthn25k_peryer <-  as.data.frame(mutate(perc_graduates_earning_grtrthn25k_peryer, Feature="Perc_graduates_earning_grtrthn25k_peryer"))

melted_df <- rbind(female_percent, percent_recv_loans, percnt_older_than_25yr,perc_graduates_earning_grtrthn25k_peryer)# mean_income_graduates_after_8yr, Avg_fam_income

melted_df$School[which(melted_df$School != "New College of Florida")] = "Other schools"

#melted_df <- as.data.frame(melted_df)
ggplot(aes(y=Value, x=Feature, fill=School), data=melted_df) + geom_boxplot()

# #Percent of all undergraduate students receiving a federal student loan
# PCTFLOAN <- c(ncf$PCTFLOAN, mean(as.numeric(outcomes2013$PCTFLOAN),na.rm=TRUE)) 
# 
# #Percentage of undergraduates aged 25 and above
# UG25ABV <- c(ncf$UG25ABV, mean(as.numeric(outcomes2013$UG25ABV), na.rm=TRUE))
# 
# #Share of female students
# FEMALE <- c(ncf$FEMALE, mean(as.numeric(outcomes2013$FEMALE), na.rm=TRUE))
# 
# #Average family income in real 2015 dollars
# FAMINC <- c(ncf$FAMINC, mean(as.numeric(outcomes2013$FAMINC), na.rm=TRUE))
# 
# #Mean earnings of students working and not enrolled 8 years after entry
# MNEARN8 <- c(ncf$MN_EARN_WNE_P8, mean(as.numeric(outcomes2013$MN_EARN_WNE_P8), na.rm=TRUE))
# 
# #Share of students earning over $25,000/year (threshold earnings) 8 years after entry
# GT25K <- c(ncf$GT_25K_P8, mean(as.numeric(outcomes2013$GT_25K_P8), na.rm=TRUE))
# 
# NAMES <- c("New College","Other Schools")
# 
# comparing_features <- c(PCTFLOAN,UG25ABV,FEMALE,FAMINC, MNEARN8, GT25K)
# df <- data.frame(NAMES, PCTFLOAN,UG25ABV,FEMALE,FAMINC, MNEARN8, GT25K)
# #row.names(df) <- c("New College","Other Schools")
```
